"""Regenerate the agent skill's bundled command reference from the live typer app.

The skill at ``skills/ytstudio/`` ships a trimmed command reference so an agent
can read the full flag surface on demand without running ``--help`` for every
command. Unlike ``docs/reference.md`` (built on the fly by mkdocs and
git-ignored), this file is checked into git because it travels with the skill
when it is installed from the repo. It must therefore be kept in sync with the
CLI: ``tests/test_skill_reference.py`` fails if the committed file drifts.

Run after changing the CLI surface:

    uv run python scripts/build_skill_reference.py
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
REFERENCE = REPO_ROOT / "skills" / "ytstudio" / "references" / "reference.md"

BANNER = (
    "<!-- Generated by scripts/build_skill_reference.py from the ytstudio CLI.\n"
    "     Do not edit by hand; run `uv run python scripts/build_skill_reference.py`. -->\n\n"
)


def render() -> str:
    """Return the command reference markdown rendered from the typer app."""
    # typer ships its own CLI; `python -m typer` avoids depending on a
    # console-script being on PATH, mirroring scripts/build_docs_reference.py.
    cmd = [
        sys.executable,
        "-m",
        "typer",
        "ytstudio.main",
        "utils",
        "docs",
        "--name",
        "ytstudio",
    ]
    result = subprocess.run(cmd, capture_output=True, text=True, check=True)

    text = result.stdout
    # Lift the top-level heading so it reads as a reference, not a command name.
    if text.lstrip().startswith("# `ytstudio`"):
        text = text.replace("# `ytstudio`", "# Command reference", 1)
    # Exactly one trailing newline, matching the end-of-file-fixer pre-commit hook
    # so the committed file and a fresh render stay byte-identical.
    return BANNER + text.strip() + "\n"


def main() -> None:
    REFERENCE.parent.mkdir(parents=True, exist_ok=True)
    REFERENCE.write_text(render())
    print(f"wrote {REFERENCE.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
