name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      coverage: true
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
